# Generated by Django 4.1.1 on 2022-10-26 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_review_stars_alter_review_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.director'),
        ),
    ]
